### ISSUE TITLE
Update breaks customized configurations

### ISSUE THREAD

**Issue by 0x46616c6b** [jitsi/jitsi-meet-debian-meta#7]
With every update of the jitsi-meet-* packages the configuration files will be overwritten with the defaults from the package. So the customizations need to re-applied every time there is an update. 

Other packages in Debian behave in another way and not overwrite the configs if there is present.

**Comment by damencho** [comment]
Can you point which files will be overwritten?

**Comment by 0x46616c6b** [comment]
This file: `/etc/jitsi/videobridge/sip-communicator.properties`.

Afterwards jicofo and jitsi-videobridge2 not working in our case.

**Comment by damencho** [comment]
We deliberately updated those. We are migrating all components to use mucs. 
If you want to stick to old config you can just add a commented line:
```
#org.jitsi.videobridge.xmpp.user.shard.MUC_JIDS
```
This is the change https://github.com/jitsi/jitsi-videobridge/blob/master/debian/postinst#L109

**Comment by 0x46616c6b** [comment]
thanks a lot for this clarification!
